config/routes.rb
Rails.application.routes.draw do

  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being the default of "spree"
        
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
    :sessions => "users/sessions", :registrations => 'users/registrations'}


  resources :attendences, :except =>[:edit] 
  resources :users, only: [:show, :update,:create,:index,:edit]
  resources :places
  resources :specialities
  resources :search_addresses, :except =>[:destroy] 
  resources :exam_types
  resources :payment_methods, only: [:show]
  resources :health_plans, only: [:show]
  resources :attendence_types, only: [:show]
  resources :service_windows, :except =>[:edit] 
  resources :payments, :only => [:index, :new]
  resources :bank_account, only: [:show]
  resources :classifications, :except =>[:edit,:destroy] 

  get 'payment/billet' => 'payments#generate_billet'

  get 'attendence/search' => 'attendences#search'
  post 'attendence/search' => 'attendences#search'
  post'attendence/create_attendences' => 'attendences#create_attendences'
  post'attendence/search_attendences' => 'attendences#search_attendences'

  post 'pagseguro/notifications' => 'notifications#create'
  post 'attendence/confirm' => 'attendences#confirm'
  post 'attendence/cancel' => 'attendences#cancel'
  post 'attendence/time' => 'attendences#time'
  post 'attendence/pag_seguro' => 'attendences#pag_seguro'

  get 'admin/create' => 'users#new'

  post 'payment/confirm' => 'payments#confirm_payment'
  post 'payment/receipt' => 'payments#confirm_receipt'
  
 devise_scope :user do
  get 'cadastro/paciente' => 'users/registrations#paciente', :as => :new_usuario_registration
  get 'cadastro/medico' => 'users/registrations#medico'
  get 'cadastro/adm',to: 'users/registrations#adm'
end

  namespace :api do

    scope :users do
      post '/sign_in_mobile',to:'/api/sessions#create', defaults: { format: 'json' }
      post '/sign_in_mobile_facebook',to:'/api/sessions#create_facebook', defaults: { format: 'json' }
      delete '/sign_out_mobile',to:'/api/sessions#destroy'
      post '/reset_password',to:'/api/sessions#reset_password'
      post '/register_mobile_multipart',to:'/api/registrations#create_multipart', defaults: { format: 'json' }
      post '/register_mobile',to:'/api/registrations#create', defaults: { format: 'json' }
  end

    post '/points', to: '/api/points#location'

    get '/attendences',to:'/api/attendences#index', defaults: { format: 'json' }

    post '/classification',to:'/api/classifications#create', defaults: { format: 'json' }

    get '/attendences/:id',to:'/api/attendences#show', defaults: { format: 'json' }

    get '/attendences/show',to:'/api/attendences#show', defaults: { format: 'json' }

    post '/attendences/confirm',to:'/api/attendences#confirm', defaults: { format: 'json' }

    get '/attendences/payment/:id',to:'/api/attendences#payment', defaults: { format: 'json' }

    post '/attendences/cancel',to:'/api/attendences#cancel', defaults: { format: 'json' }

    post '/attendences/time',to:'/api/attendences#time', defaults: { format: 'json' }

    get '/specialities',to:'/api/specialities#index', defaults: { format: 'json' }

    get '/exam_types',to:'/api/exam_types#index', defaults: { format: 'json' }

    get '/payment_methods',to:'/api/payment_methods#index', defaults: { format: 'json' }

    get '/health_plans',to:'/api/health_plans#index', defaults: { format: 'json' }

    get '/attendence_types',to:'/api/attendence_types#index', defaults: { format: 'json' }

    post '/device_id',to:'/api/device_ids#create', defaults: { format: 'json' } 

    get '/current_user',to:'/api/users#current_user_session', defaults: { format: 'json' }

    post '/attendences/search_attendence_home_care',to:'/api/attendences#search_attendences_home_care', defaults: { format: 'json' }    
 
    post '/attendences/search_attendence_clinic',to:'/api/attendences#search_attendences_clinic', defaults: { format: 'json' }

    post '/attendences/create_attendence',to:'/api/attendences#create_attendences', defaults: { format: 'json' }

  end

 
  root :to => 'attendences#index'


end

app/controllers/search_addresses_controller.rb
class SearchAddressesController < ApplicationController
  before_action :set_search_address, only: [:show, :edit, :update, :destroy]
before_action :authenticate_user!
    skip_before_filter  :verify_authenticity_token
  # GET /search_addresses
  # GET /search_addresses.json
  def index
    @search_addresses = SearchAddress.all
  end

  # GET /search_addresses/1
  # GET /search_addresses/1.json
  def show
  end

  # GET /search_addresses/new
  def new
    @search_address = SearchAddress.new
    @attendence = @search_address.attendence.build
  end

  # GET /search_addresses/1/edit
  def edit
  end

  # POST /search_addresses
  # POST /search_addresses.json
  def create
    @search_address = SearchAddress.new(search_address_params)
    
    respond_to do |format|
      if @search_address.save
        @attendence.save
        format.html { redirect_to @search_address, notice: 'Search address was successfully created.' }
        format.json { render :show, status: :created, location: @search_address }
      else
        format.html { render :new }
        format.json { render json: @search_address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /search_addresses/1
  # PATCH/PUT /search_addresses/1.json
  def update
    respond_to do |format|
      if @search_address.update(search_address_params)
        format.html { redirect_to @search_address, notice: 'Search address was successfully updated.' }
        format.json { render :show, status: :ok, location: @search_address }
      else
        format.html { render :edit }
        format.json { render json: @search_address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /search_addresses/1
  # DELETE /search_addresses/1.json
  def destroy
    @search_address.destroy
    respond_to do |format|
      format.html { redirect_to search_addresses_url, notice: 'Search address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_search_address
      @search_address = SearchAddress.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def search_address_params
      params.require(:search_address).permit(:address, :complement, :latitude, :longitude, :user_id)
    end
end

app/helpers/search_addresses_helper.rb
module SearchAddressesHelper
end

app/views/search_addresses/_form.html.erb
<%= javascript_include_tag "place" %>
<% content_for :css do %>
  <link rel="stylesheet" href="/stylesheets/places.css">
<% end %>

<h1>Procurar atendimento</h1>
<div class="preto"> </div>

<%= form_tag attendence_search_attendences_path do %> 

<div class = 'map_tudo'>
  <div class = "mapacampos">
        <div class="text_search">
          <%= text_field_tag :address,params[:address], placeholder:"Selecione sua localização",id:"Endereco",size: "165px"%> 
        </div>

        <%= hidden_field_tag :latitude, id:"latitude"%>

        <%= hidden_field_tag :longitude, id:"longitude"%>

     <div class= "search_but"> <%= link_to "Proxímo", attendence_search_attendences_path, remote: true %> </div>
  </div>

<% end %>


<div id="mapa" style="height: 100%; width: 100%; margin-top:-2px;"></div>
</div>



<script type="text/javascript">

function getUrlVars() {
    var vars = {};
    var parts = window.location.href.replace(/[?&]+([^=&]+)=([^&]*)/gi,    
    function(m,key,value) {
      vars[key] = value;
    });
    return vars;
  }


$('.search_but').on("click", function() {
          var result_exame = getUrlVars()["exam"]
          var result_speciality = getUrlVars()["speciality"]

          var address =  $('#Endereco').val();
          var latitude = $('#latitude').val();
          var longitude =  $('#longitude').val();
          var speciality = getUrlVars()["speciality"];
          var payment =  getUrlVars()["payment"];
          var health_plan = getUrlVars()["health_plan"];
          var attendence_type = getUrlVars()["attendence_type"];

          if (result_exame != "") 
          var exam =  getUrlVars()["exam"]
        
          if (result_exame == "")
          var exam =  getUrlVars()["exam_home"]
        
          if (result_speciality != "") 
          var speciality = getUrlVars()["speciality"]

          if (result_speciality == "") 
          var speciality =  getUrlVars()["speciality_home"]


          $.ajax({
              type: "post",
              url: "/attendence/search_attendences",

              data: {address,latitude,longitude,payment,health_plan,exam,speciality,attendence_type},
              success: function (data){

            }
          });
      });


</script>

app/views/search_addresses/edit.html.erb
<h1>Editing Search Address</h1>

<%= render 'form' %>

<%= link_to 'Show', @search_address %> |
<%= link_to 'Back', search_addresses_path %>

app/views/search_addresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Search Addresses</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Complement</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @search_addresses.each do |search_address| %>
      <tr>
        <td><%= search_address.address %></td>
        <td><%= search_address.complement %></td>
        <td><%= search_address.latitude %></td>
        <td><%= search_address.longitude %></td>
        <td><%= search_address.user %></td>
        <td><%= link_to 'Show', search_address %></td>
        <td><%= link_to 'Edit', edit_search_address_path(search_address) %></td>
        <td><%= link_to 'Destroy', search_address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Search address', new_search_address_path %>

app/views/search_addresses/new.html.erb
<%= render 'form' %>

app/views/search_addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @search_address.address %>
</p>

<p>
  <strong>Complement:</strong>
  <%= @search_address.complement %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @search_address.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @search_address.longitude %>
</p>

<p>
  <strong>User:</strong>
  <%= @search_address.user %>
</p>

<%= link_to 'Edit', edit_search_address_path(@search_address) %> |
<%= link_to 'Back', search_addresses_path %>