config/routes.rb
Rails.application.routes.draw do

  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being the default of "spree"
        
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
    :sessions => "users/sessions", :registrations => 'users/registrations'}


  resources :attendences, :except =>[:edit] 
  resources :users, only: [:show, :update,:create,:index,:edit]
  resources :places
  resources :specialities
  resources :search_addresses, :except =>[:destroy] 
  resources :exam_types
  resources :payment_methods, only: [:show]
  resources :health_plans, only: [:show]
  resources :attendence_types, only: [:show]
  resources :service_windows, :except =>[:edit] 
  resources :payments, :only => [:index, :new]
  resources :bank_account, only: [:show]
  resources :classifications, :except =>[:edit,:destroy] 

  get 'payment/billet' => 'payments#generate_billet'

  get 'attendence/search' => 'attendences#search'
  post 'attendence/search' => 'attendences#search'
  post'attendence/create_attendences' => 'attendences#create_attendences'
  post'attendence/search_attendences' => 'attendences#search_attendences'

  post 'pagseguro/notifications' => 'notifications#create'
  post 'attendence/confirm' => 'attendences#confirm'
  post 'attendence/cancel' => 'attendences#cancel'
  post 'attendence/time' => 'attendences#time'
  post 'attendence/pag_seguro' => 'attendences#pag_seguro'

  get 'admin/create' => 'users#new'

  post 'payment/confirm' => 'payments#confirm_payment'
  post 'payment/receipt' => 'payments#confirm_receipt'
  
 devise_scope :user do
  get 'cadastro/paciente' => 'users/registrations#paciente', :as => :new_usuario_registration
  get 'cadastro/medico' => 'users/registrations#medico'
  get 'cadastro/adm',to: 'users/registrations#adm'
end

  namespace :api do

    scope :users do
      post '/sign_in_mobile',to:'/api/sessions#create', defaults: { format: 'json' }
      post '/sign_in_mobile_facebook',to:'/api/sessions#create_facebook', defaults: { format: 'json' }
      delete '/sign_out_mobile',to:'/api/sessions#destroy'
      post '/reset_password',to:'/api/sessions#reset_password'
      post '/register_mobile_multipart',to:'/api/registrations#create_multipart', defaults: { format: 'json' }
      post '/register_mobile',to:'/api/registrations#create', defaults: { format: 'json' }
  end

    post '/points', to: '/api/points#location'

    get '/attendences',to:'/api/attendences#index', defaults: { format: 'json' }

    post '/classification',to:'/api/classifications#create', defaults: { format: 'json' }

    get '/attendences/:id',to:'/api/attendences#show', defaults: { format: 'json' }

    get '/attendences/show',to:'/api/attendences#show', defaults: { format: 'json' }

    post '/attendences/confirm',to:'/api/attendences#confirm', defaults: { format: 'json' }

    get '/attendences/payment/:id',to:'/api/attendences#payment', defaults: { format: 'json' }

    post '/attendences/cancel',to:'/api/attendences#cancel', defaults: { format: 'json' }

    post '/attendences/time',to:'/api/attendences#time', defaults: { format: 'json' }

    get '/specialities',to:'/api/specialities#index', defaults: { format: 'json' }

    get '/exam_types',to:'/api/exam_types#index', defaults: { format: 'json' }

    get '/payment_methods',to:'/api/payment_methods#index', defaults: { format: 'json' }

    get '/health_plans',to:'/api/health_plans#index', defaults: { format: 'json' }

    get '/attendence_types',to:'/api/attendence_types#index', defaults: { format: 'json' }

    post '/device_id',to:'/api/device_ids#create', defaults: { format: 'json' } 

    get '/current_user',to:'/api/users#current_user_session', defaults: { format: 'json' }

    post '/attendences/search_attendence_home_care',to:'/api/attendences#search_attendences_home_care', defaults: { format: 'json' }    
 
    post '/attendences/search_attendence_clinic',to:'/api/attendences#search_attendences_clinic', defaults: { format: 'json' }

    post '/attendences/create_attendence',to:'/api/attendences#create_attendences', defaults: { format: 'json' }

  end

 
  root :to => 'attendences#index'


end

app/models/bank_account.rb
class BankAccount < ActiveRecord::Base
	belongs_to :user

	validates :bank,:presence => { :message => "^Banco não pode estar em branco"}
	validates :full_name,:presence => { :message => "^Digite seu nome completo"}
	validates :cpf_cnpj,:presence => { :message => "^Digite seu cpf ou cnpj"},:numericality => { :message => "^Digite apenas números no seu cpf ou cnpj"}
	validates :account,:presence => { :message => "^Digite o numero da sua conta"}
	validates :agency,:presence => { :message => "^Digite o numero da sua agencia"}
	
end

app/controllers/bank_accounts_controller.rb
class BankAccountsController < ApplicationController
  before_action :set_bank_account, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /bank_accounts
  # GET /bank_accounts.json
  def index
    @bank_accounts = BankAccount.all
  end

  # GET /bank_accounts/1
  # GET /bank_accounts/1.json
  def show
  end

  # GET /bank_accounts/new
  def new
    @bank_account = BankAccount.new

  end

  # GET /bank_accounts/1/edit
  def edit
  end

  # POST /bank_accounts
  # POST /bank_accounts.json
  def create
    @bank_account = BankAccount.new(bank_account_params)

    respond_to do |format|
      if @bank_account.save
        format.html { redirect_to @bank_account, notice: 'Bank account was successfully created.' }
        format.json { render :show, status: :created, location: @bank_account }
      else
        format.html { render :new }
        format.json { render json: @bank_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bank_accounts/1
  # PATCH/PUT /bank_accounts/1.json
  def update
    respond_to do |format|
      if @bank_account.update(bank_account_params)
        format.html { redirect_to @bank_account, notice: 'Bank account was successfully updated.' }
        format.json { render :show, status: :ok, location: @bank_account }
      else
        format.html { render :edit }
        format.json { render json: @bank_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bank_accounts/1
  # DELETE /bank_accounts/1.json
  def destroy
    @bank_account.destroy
    respond_to do |format|
      format.html { redirect_to bank_accounts_url, notice: 'Bank account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bank_account
      @bank_account = BankAccount.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bank_account_params
      params.require(:bank_account).permit(:bank, :full_name, :cpf_cnpj, :account, :operation, :user,:agency)
    end
end

app/helpers/bank_accounts_helper.rb
module BankAccountsHelper
end

app/views/bank_accounts/_form.html.erb
<%= form_for(@bank_account) do |f| %>
  <% if @bank_account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bank_account.errors.count, "error") %> prohibited this bank_account from being saved:</h2>

      <ul>
      <% @bank_account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :bank %><br>
    <%= f.text_field :bank %>
  </div>
  <div class="field">
    <%= f.label :full_name %><br>
    <%= f.text_field :full_name %>
  </div>
  <div class="field">
    <%= f.label :cpf_cnpj %><br>
    <%= f.text_field :cpf_cnpj %>
  </div>
  <div class="field">
    <%= f.label :account %><br>
    <%= f.text_field :account %>
  </div>
  <div class="field">
    <%= f.label :operation %><br>
    <%= f.text_field :operation %>
  </div>
  <div class="field">
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bank_accounts/edit.html.erb
<h1>Editing Bank Account</h1>

<%= render 'form' %>

<%= link_to 'Show', @bank_account %> |
<%= link_to 'Back', bank_accounts_path %>

app/views/bank_accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bank Accounts</h1>

<table>
  <thead>
    <tr>
      <th>Bank</th>
      <th>Full name</th>
      <th>Cpf cnpj</th>
      <th>Account</th>
      <th>Operation</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bank_accounts.each do |bank_account| %>
      <tr>
        <td><%= bank_account.bank %></td>
        <td><%= bank_account.full_name %></td>
        <td><%= bank_account.cpf_cnpj %></td>
        <td><%= bank_account.account %></td>
        <td><%= bank_account.operation %></td>
        <td><%= bank_account.user %></td>
        <td><%= link_to 'Show', bank_account %></td>
        <td><%= link_to 'Edit', edit_bank_account_path(bank_account) %></td>
        <td><%= link_to 'Destroy', bank_account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bank account', new_bank_account_path %>

app/views/bank_accounts/new.html.erb
<h1>New Bank Account</h1>

<%= render 'form' %>

<%= link_to 'Back', bank_accounts_path %>

app/views/bank_accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bank:</strong>
  <%= @bank_account.bank %>
</p>

<p>
  <strong>Full name:</strong>
  <%= @bank_account.full_name %>
</p>

<p>
  <strong>Cpf cnpj:</strong>
  <%= @bank_account.cpf_cnpj %>
</p>

<p>
  <strong>Account:</strong>
  <%= @bank_account.account %>
</p>

<p>
  <strong>Operation:</strong>
  <%= @bank_account.operation %>
</p>

<p>
  <strong>User:</strong>
  <%= @bank_account.user %>
</p>

<%= link_to 'Edit', edit_bank_account_path(@bank_account) %> |
<%= link_to 'Back', bank_accounts_path %>