config/routes.rb
Rails.application.routes.draw do

  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being the default of "spree"
        
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
    :sessions => "users/sessions", :registrations => 'users/registrations'}


  resources :attendences, :except =>[:edit] 
  resources :users, only: [:show, :update,:create,:index,:edit]
  resources :places
  resources :specialities
  resources :search_addresses, :except =>[:destroy] 
  resources :exam_types
  resources :payment_methods, only: [:show]
  resources :health_plans, only: [:show]
  resources :attendence_types, only: [:show]
  resources :service_windows, :except =>[:edit] 
  resources :payments, :only => [:index, :new]
  resources :bank_account, only: [:show]
  resources :classifications, :except =>[:edit,:destroy] 

  get 'payment/billet' => 'payments#generate_billet'

  get 'attendence/search' => 'attendences#search'
  post 'attendence/search' => 'attendences#search'
  post'attendence/create_attendences' => 'attendences#create_attendences'
  post'attendence/search_attendences' => 'attendences#search_attendences'

  post 'pagseguro/notifications' => 'notifications#create'
  post 'attendence/confirm' => 'attendences#confirm'
  post 'attendence/cancel' => 'attendences#cancel'
  post 'attendence/time' => 'attendences#time'
  post 'attendence/pag_seguro' => 'attendences#pag_seguro'

  get 'admin/create' => 'users#new'

  post 'payment/confirm' => 'payments#confirm_payment'
  post 'payment/receipt' => 'payments#confirm_receipt'
  
 devise_scope :user do
  get 'cadastro/paciente' => 'users/registrations#paciente', :as => :new_usuario_registration
  get 'cadastro/medico' => 'users/registrations#medico'
  get 'cadastro/adm',to: 'users/registrations#adm'
end

  namespace :api do

    scope :users do
      post '/sign_in_mobile',to:'/api/sessions#create', defaults: { format: 'json' }
      post '/sign_in_mobile_facebook',to:'/api/sessions#create_facebook', defaults: { format: 'json' }
      delete '/sign_out_mobile',to:'/api/sessions#destroy'
      post '/reset_password',to:'/api/sessions#reset_password'
      post '/register_mobile_multipart',to:'/api/registrations#create_multipart', defaults: { format: 'json' }
      post '/register_mobile',to:'/api/registrations#create', defaults: { format: 'json' }
  end

    post '/points', to: '/api/points#location'

    get '/attendences',to:'/api/attendences#index', defaults: { format: 'json' }

    post '/classification',to:'/api/classifications#create', defaults: { format: 'json' }

    get '/attendences/:id',to:'/api/attendences#show', defaults: { format: 'json' }

    get '/attendences/show',to:'/api/attendences#show', defaults: { format: 'json' }

    post '/attendences/confirm',to:'/api/attendences#confirm', defaults: { format: 'json' }

    get '/attendences/payment/:id',to:'/api/attendences#payment', defaults: { format: 'json' }

    post '/attendences/cancel',to:'/api/attendences#cancel', defaults: { format: 'json' }

    post '/attendences/time',to:'/api/attendences#time', defaults: { format: 'json' }

    get '/specialities',to:'/api/specialities#index', defaults: { format: 'json' }

    get '/exam_types',to:'/api/exam_types#index', defaults: { format: 'json' }

    get '/payment_methods',to:'/api/payment_methods#index', defaults: { format: 'json' }

    get '/health_plans',to:'/api/health_plans#index', defaults: { format: 'json' }

    get '/attendence_types',to:'/api/attendence_types#index', defaults: { format: 'json' }

    post '/device_id',to:'/api/device_ids#create', defaults: { format: 'json' } 

    get '/current_user',to:'/api/users#current_user_session', defaults: { format: 'json' }

    post '/attendences/search_attendence_home_care',to:'/api/attendences#search_attendences_home_care', defaults: { format: 'json' }    
 
    post '/attendences/search_attendence_clinic',to:'/api/attendences#search_attendences_clinic', defaults: { format: 'json' }

    post '/attendences/create_attendence',to:'/api/attendences#create_attendences', defaults: { format: 'json' }

  end

 
  root :to => 'attendences#index'


end

app/models/place.rb
class Place < ActiveRecord::Base
		  
  belongs_to :user
  has_many :service_window,:dependent => :destroy
  has_many :attendence, :dependent => :destroy

    acts_as_mappable :default_units => :kms,
                   :default_formula => :sphere,
                   :distance_field_name => :distance,
                   :lat_column_name => :latitude,
                   :lng_column_name => :longitude

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /places
  # GET /places.json
  def index
    @places = Place.where(user_id: current_user).order("created_at DESC")
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)
    @place.user = current_user

    respond_to do |format|
      if @place.save
        format.html { redirect_to places_url}
        format.json { render :index, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to places_url, notice: 'Local editado com sucesso.' }
        format.json { render :index, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
  @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Local deletado com sucesso.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name, :address, :complement, :latitude, :longitude,:user_id)
    end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<% content_for :css do %>
  <link rel="stylesheet" href="/stylesheets/places.css">
<% end %>
  

  
<%= form_for(@place) do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>
      <ul>
      <% @place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class = "mapacampos">
      
        <%= f.text_field :name, placeholder: "Nome", size: "40px"%> 
 
       <%= f.text_field :address,  placeholder:"Endereço",id:"Endereco",size: "45px" %> 
       
       <%= f.text_field :complement,  placeholder: "Compl",size: "17px" %> 

       <%= f.hidden_field :latitude, id:"latitude"%>
 
       <%= f.hidden_field :longitude, id:"longitude"%>

       <%= f.hidden_field :user_id%>

       <button class="but4" type="submit">Criar local de atendimento</button></div>
 
<% end %>

<div id="mapa" style="height: 100%; width: 100%; margin-top:-15px;"></div>

app/views/places/edit.html.erb
<h1>Editar local</h1>
<div class="preto"> </div>

<%= form_for(@place) do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>
      <ul>
      <% @place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class = "mapacampos">
      
        <%= f.text_field :name, placeholder: "Nome", size: "23px"%> 
 
       <%= f.text_field :address,  placeholder:"Endereço",id:"Endereco",size: "32px",autocomplete: true %> 
       
       <%= f.text_field :complement,  placeholder: "Compl",size: "17px" %> 

       <%= f.hidden_field :latitude, id:"latitude"%>
 
       <%= f.hidden_field :longitude, id:"longitude"%>

       <div class="field" hidden ="true"> <%= f.text_field :user_id %>  </div>

       <button class="but4" type="submit">Editar local de atendimento</button></div>
 
<% end %>

<div id="mapa" style="height: 100%; width: 100%"></div>

app/views/places/index.html.erb
<%= stylesheet_link_tag "places", media: "all" %>
<div class="locais_titulo"><h1>Locais de Atendimentos</h1></div>

<div class="preto"> </div>
 
	<table class="table table-striped">
  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= place.name %></td>
        <td> <%= link_to image_tag("/assets/multimedia.png"),edit_place_path(place) %></td>
        <td><%= link_to image_tag("/assets/garbage.png"), place, method: :delete, data: { confirm: 'Tem certeza? Todos as seus consultas e suas janelas de atendimento neste local também serão deletados.' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div id="topo">
  
</div>

<div class="bot">
  <img src="/assets/new.png">
  <%= link_to 'Novo local de atendimento', new_place_path%>
</div>

app/views/places/new.html.erb
<h1>Locais de Atendimento</h1>
<div class="preto"> </div>

<%= render 'form' %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @place.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @place.address %>
</p>

<p>
  <strong>Complement:</strong>
  <%= @place.complement %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @place.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @place.longitude %>
</p>

<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>